apiVersion: v1
kind: Service
metadata:
  name: email-core-engine-service
spec:
  type: ClusterIP
  selector:
    app: email-core-engine
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
